Multiple Linear Regression using Matrix

In [1]:
import  pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
from sklearn.datasets import fetch_california_housing

In [4]:
data=fetch_california_housing()

In [22]:
data=pd.DataFrame(data.data,columns=data.feature_names)

In [19]:
x=pd.DataFrame(data.data,columns=data.feature_names)
y=pd.DataFrame(data.target,columns=data.target_names)

x.insert(0,"Temp",1)

In [20]:
x

,Temp,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,1,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,1,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,1,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,1,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...,...
20635,1,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,1,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,1,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [ ]:
X_T=x.T

In [25]:
print("x_shape",x.shape,"  y_shape",y.shape," X_T shape",X_T.shape)

x_shape (20640, 9)   y_shape (20640, 1)  X_T shape (9, 20640)

In [28]:
x=np.array(x)
y=np.array(y)

In [33]:
b=(np.linalg.inv(X_T@x))@(X_T@y)

In [34]:
b

           0
0 -36.941920
1   0.436693
2   0.009436
3  -0.107322
4   0.645066
5  -0.000004
6  -0.003787
7  -0.421314
8  -0.434514

In [71]:
y_pred= x @ b

In [72]:
y_pred=y_pred[0:]
y_pred

              0
0      4.131650
1      3.976606
2      3.676571
3      3.241598
4      2.413587
...         ...
20635  0.133656
20636  0.553528
20637  0.171251
20638  0.319105
20639  0.515804

[20640 rows x 1 columns]

In [89]:
SSE=np.sum(y-y_pred)

In [90]:
MSE=SSE**2

In [91]:
MSE

0    5.514272e-14
dtype: float64

In [59]:
print(y,y_pred)

[[4.526]
 [3.585]
 [3.521]
 ...
 [0.923]
 [0.847]
 [0.894]]               0
0      4.131650
1      3.976606
2      3.676571
3      3.241598
4      2.413587
...         ...
20635  0.133656
20636  0.553528
20637  0.171251
20638  0.319105
20639  0.515804

[20640 rows x 1 columns]