
### You are given a dataset – “hotel_bookings.csv.” The dataset has a high number of null and  elements that need to be cleansed;  Your job is to create a separate DataFrame with only categorical columns and  perform the  following operations:
### 1.	Find the number of null values in each column of the new DataFrame
### 2.	Replace the null values with mode 
### 3.	In the "hotel" column, replace the hotel names with "0" and "1" based on the condition that – if, "hotel" = "city_hotel", then "hotel" = "1";  else, "0"
### 4.	Using the label encoder, assign a unique country code to each country
### 5.	Using onehot encoder, encode the “month” column

In [1]:
import numpy as np
import pandas as pd
import sklearn

hotel_book= pd.read_csv('hotel_bookings.csv') 
hotel_book

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [2]:
hotel_book.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

In [3]:
hotel_book.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [4]:
hotel_book.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [5]:
hotel_book=hotel_book.drop(['company','agent'],axis=1)
hotel_book

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,assigned_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,C,3,No Deposit,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,C,4,No Deposit,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,C,0,No Deposit,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,A,0,No Deposit,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,A,0,No Deposit,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,A,0,No Deposit,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,E,0,No Deposit,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,D,0,No Deposit,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,A,0,No Deposit,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,A,0,No Deposit,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [6]:
hotel_book.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 30 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  days_in_waiting_list            119390 non-null  int64
 24  customer_type                   119390 non-null  object
 25  adr                             119390 non-null  float64
 26  required_car_parking_spaces     119390 non-null  int64
 27  total_of_special_requests       119390 non-null  int64
 28  reservation_status              119390 non-null  object
 29  reservation_status_date         119390 non-null  object
dtypes: float64(2), int64(16), object(12)
memory usage: 27.3+ MB

In [7]:
hotel_book.isnull().sum()

hotel                               0
is_canceled                         0
lead_time                           0
arrival_date_year                   0
arrival_date_month                  0
arrival_date_week_number            0
arrival_date_day_of_month           0
stays_in_weekend_nights             0
stays_in_week_nights                0
adults                              0
children                            4
babies                              0
meal                                0
country                           488
market_segment                      0
distribution_channel                0
is_repeated_guest                   0
previous_cancellations              0
previous_bookings_not_canceled      0
reserved_room_type                  0
assigned_room_type                  0
booking_changes                     0
deposit_type                        0
days_in_waiting_list                0
customer_type                       0
adr                                 0
required_car_parking_spaces         0
total_of_special_requests           0
reservation_status                  0
reservation_status_date             0
dtype: int64

In [8]:
hotel_book['country'].value_counts()

country
PRT    48590
GBR    12129
FRA    10415
ESP     8568
DEU     7287
       ...
DJI        1
BWA        1
HND        1
VGB        1
NAM        1
Name: count, Length: 177, dtype: int64

In [9]:
hotel_book['country'].value_counts().index[0]

'PRT'

In [10]:
hotel_book=hotel_book.fillna(hotel_book['country'].value_counts().index[0])

In [12]:
import numpy as np
import pandas as pd
import sklearn

hotel_book= pd.read_csv('hotel_bookings.csv') 
hotel_book

hotel_book.head(5)
hotel_book.tail(5)
hotel_book.sample(5)
hotel_book.describe()

hotel_book.isnull()
hotel_book.isnull().any()


#Find the number of null values in each column of the new DataFrame
hotel_book.isnull().sum()
hotel_book=hotel_book.drop(['company','agent'],axis=1)
hotel_book


#Replace the null values with mode
hotel_book=hotel_book.fillna(hotel_book['country'].value_counts().index[0])
hotel_book
hotel_book.isnull().sum()


# In the "hotel" column, replace the hotel names with "0" and "1" based on the condition that 
# – if, "hotel" = "city_hotel", then "hotel" = "1"; else, "0"
hotel_book['hotel']=np.where(hotel_book['hotel'].str.contains('City Hotel'),1,0)
hotel_book
hotel_book.sample(5)


# Using the label encoder, assign a unique country code to each country
from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder()
hotel_book['country code']=LE.fit_transform(hotel_book['country'])
hotel_book

# OR

LE=LabelEncoder()
hotel_book['country']=LE.fit_transform(hotel_book['country'])
hotel_book

hotel_book.sample(5)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,country code
61818,1,1,355,2016,December,53,26,2,5,2,...,0,No Deposit,0,Transient,87.31,0,0,Canceled,2016-05-22,83
63311,1,1,59,2017,February,6,7,0,2,2,...,0,No Deposit,0,Transient,102.06,0,2,Canceled,2017-01-12,31
98813,1,0,16,2016,October,41,2,2,1,1,...,0,No Deposit,0,Transient,95.00,0,0,Check-Out,2016-10-05,29
57197,1,1,1,2016,September,39,20,0,3,2,...,0,No Deposit,0,Transient,160.00,0,0,No-Show,2016-09-20,135
69180,1,1,235,2017,May,21,26,1,2,2,...,0,No Deposit,0,Transient,107.10,0,1,Canceled,2017-01-05,59

In [13]:
# USING get_dummies()

hotel_book=pd.DataFrame(hotel_book)
hotel_book
hotel_book = pd.get_dummies(hotel_book, columns=['arrival_date_month'], prefix='month', drop_first=False)
print(hotel_book)

        hotel  is_canceled  lead_time  arrival_date_year  \
0           0            0        342               2015
1           0            0        737               2015
2           0            0          7               2015
3           0            0         13               2015
4           0            0         14               2015
...       ...          ...        ...                ...
119385      1            0         23               2017
119386      1            0        102               2017
119387      1            0         34               2017
119388      1            0        109               2017
119389      1            0        205               2017

        arrival_date_week_number  arrival_date_day_of_month  \
0                             27                          1
1                             27                          1
2                             27                          1
3                             27                          1
4                             27                          1
...                          ...                        ...
119385                        35                         30
119386                        35                         31
119387                        35                         31
119388                        35                         31
119389                        35                         29

        stays_in_weekend_nights  stays_in_week_nights  adults children  ...  \
0                             0                     0       2      0.0  ...
1                             0                     0       2      0.0  ...
2                             0                     1       1      0.0  ...
3                             0                     1       1      0.0  ...
4                             0                     2       2      0.0  ...
...                         ...                   ...     ...      ...  ...
119385                        2                     5       2      0.0  ...
119386                        2                     5       3      0.0  ...
119387                        2                     5       2      0.0  ...
119388                        2                     5       2      0.0  ...
119389                        2                     7       2      0.0  ...

        month_December month_February  month_January month_July month_June  \
0                False          False          False       True      False
1                False          False          False       True      False
2                False          False          False       True      False
3                False          False          False       True      False
4                False          False          False       True      False
...                ...            ...            ...        ...        ...
119385           False          False          False      False      False
119386           False          False          False      False      False
119387           False          False          False      False      False
119388           False          False          False      False      False
119389           False          False          False      False      False

        month_March  month_May  month_November month_October month_September
0             False      False           False         False           False
1             False      False           False         False           False
2             False      False           False         False           False
3             False      False           False         False           False
4             False      False           False         False           False
...             ...        ...             ...           ...             ...
119385        False      False           False         False           False
119386        False      False           False         False           False
119387        False      False           False         False           False
119388        False      False           False         False           False
119389        False      False           False         False           False

[119390 rows x 42 columns]

In [ ]:


# Using onehot encoder, encode the “month” column
# from sklearn.preprocessing import OneHotEncoder
# OHE=OneHotEncoder()
# hotel_book['month']=OHE.fit_transform(hotel_book['arrival_date_month'])
# hotel_book

# VALUE ERROR: Expected 2D array, got 1D array instead
# SOLUTION: 
#OHE = OneHotEncoder(sparse=False, drop=None)
#sparse=False: This ensures the output is a dense NumPy array, not a sparse matrix.
             # It allows easy conversion into a Pandas DataFrame.
# drop=None: This means no category will be dropped, so you'll get one column for each unique category in your input.
             #Use drop='first' if you want to drop the first category to avoid multicollinearity in regression models.

# Reshape to 2D array
month_encoded = OHE.fit_transform(hotel_book[['arrival_date_month']])
# Convert to DataFrame with appropriate column names
month_df = pd.DataFrame(month_encoded, columns=OHE.get_feature_names_out(['arrival_date_month']))
# Concatenate with original DataFrame
hotel_book = pd.concat([hotel_book.drop('arrival_date_month', axis=1), month_df], axis=1)



# USING RESHAPE
# Convert column to NumPy array and reshape to 2D
month_array = hotel_book['arrival_date_month'].to_numpy().reshape(-1, 1)
# Fit and transform the reshaped array
month_encoded = OHE.fit_transform(month_array)
# Create DataFrame from encoded array
month_df = pd.DataFrame(month_encoded, columns=OHE.get_feature_names_out(['arrival_date_month']))
#Align indexes to avoid issues during concatenation
month_df.index = hotel_book.index
#Replace original column with new encoded columns
hotel_book = pd.concat([hotel_book.drop('arrival_date_month', axis=1), month_df], axis=1)

## Scaling the Data

### 1. Min-Max Scalar

#### USing Library

In [ ]:
from sklearn.preprocessing import MinMaxScaler

minmax = MinMaxScaler()

# minmax = MinMaxScalar(feature_range=(10, 20))

In [ ]:
# column data
x=hotel_book['lead_time']
x

In [ ]:
 hotel_book['lead_time']= minmax.fit_transform(hotel_book[['lead_time']])

In [ ]:
hotel_book

#### Using Scrach [X= (X - X_min)/ (X_max - X_min)]

In [ ]:
lt=hotel_book['lead_time']
lt

In [ ]:
hotel_book['lead_time']=(lt - lt.min()) / (lt.max() - lt.min())

In [ ]:
hotel_book

In [ ]:
hotel_book1 = hotel_book.copy()

min_val = hotel_book['lead_time'].min()
max_val = hotel_book['lead_time'].max()

hotel_book1['lead_time'] = (hotel_book['lead_time'] - min_val) / (max_val - min_val)

In [ ]:
hotel_book1 = hotel_book.copy()

x = ['lead_time']

for col in x:
    min_val = hotel_book[col].min()
    max_val = hotel_book[col].max()
    hotel_book1[col + '_scaled'] = (hotel_book[col] - min_val) / (max_val - min_val)

print(hotel_book)

### 2. Standard Scalar

#### using library

In [ ]:
from sklearn.preprocessing import StandardScaler

ss= StandardScaler()
hotel_book['lead_time'] = ss.fit_transform(hotel_book[['lead_time']])
print(hotel_book['lead_time'])

#### using Scratch 

#### X = X - mean / sd

In [ ]:
lt=hotel_book['lead_time']
lt
mean = lt.mean()
std = lt.std()
hotel_book['lead_time'] = (lt - mean) / std
print(hotel_book)

### 3. Robust Scaling

#### Using Library

In [ ]:
from sklearn.preprocessing import RobustScaler

robust = RobustScaler()
hotel_book['lead_time'] = robust.fit_transform(hotel_book[['lead_time']])
print(hotel_book['lead_time'] )

#### Using Scratch

#### X = (X - median) / IQR

#### IQR= Q_3 - Q_1

In [ ]:
lt=hotel_book['lead_time']
lt

q1 = lt.quantile(0.25)
q3 = lt.quantile(0.75)
iqr = q3 - q1
median = lt.median()
hotel_book['lead_time'] = (lt - median) / iqr
print(hotel_book['lead_time'] )

### Normlization

In [ ]:
import pandas as pd
from sklearn.preprocessing import normalize
import numpy as np

In [ ]:
lt=hotel_book[['lead_time']].values
lt

In [ ]:
norm=normalize(lt)

hotel_book['lead_time']=norm

print(hotel_book)

#### Normalization (specifically L2 normalization) scales the values so that the
#### entire row (or feature vector) has a unit norm (length = 1)


#### X_norm = X/sqrt(X^2)

In [ ]:
hotel_book1 = hotel_book.copy()

l2_norm = np.sqrt((hotel_book1['lead_time']**2).sum())

In [ ]:
hotel_book1['lead_time'] = hotel_book1['lead_time'] / l2_norm
print(hotel_book)

### You are given a dataset – “Heart_Disease.csv.” The dataset has a high number of null and elements that need to be cleansed;
### 1. Find the number of null values in each column of the new DataFrame.
### 2. Perform feature scaling on the numerical columns of the dataset using the following techniques:
### (min max scalar, standard scalar, Robust Scalar)
### 3. Use Data Normalization